name = "luukahead"
main = "./.svelte-kit/cloudflare-workers/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-23"

# no clue what this does but replaces: site = { bucket = "./static" }
[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

# Ensures we have a binding to a D1 database
[[d1_databases]]
binding = "DB"
database_name = "kablan_db"
database_id = "01ca3af7-978a-4258-9ad1-37ae8f060510"
migrations_dir = "./drizzle"

# Environment variables (non-secret values)
[vars]
GOOGLE_CLIENT_ID = "your-client-id"
GOOGLE_REDIRECT_URI = "http://luukahead.kablan.nl/login/google/callback"
MICROSOFT_CLIENT_ID = "e393ab40-63b6-4ce3-9058-867b937662c5"
MICROSOFT_REDIRECT_URI = "http://luukahead.kablan.nl/login/microsoft/callback"

# Enables Logging for the worker
[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.